### ISSUE TITLE
Could images for slides be generated to have a max size that is equal to the slide size?

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/md2googleslides#23]
Currently, many of the tables we are generating are so large that it's a lot of work to get to the edge of them to shrink them to fit the slides. I can't think of a single use case where we would want an image or a table to generate at a size that is larger than the slide and I'm pretty sure that with the number of slide decks we have it will save hours of authoring cleanup work to generate them at a scale where we can grab a corner to resize on first view.

Ideally, no image would be taller than the part of the slide that is below the title or wider than the slide.

**Comment by schanzer** [comment]
@flannery-denny moving to md2googleslides, since this is about how images are positioned and all tables are images

**Comment by retabak** [comment]
THIS WOULD BE AMAZING! what a great and obvious idea (that I did not think of). 

any of the early math slide decks are good examples too!

**Comment by schanzer** [comment]
@flannery-denny and @retabak this should now be fixed. I tested it out on `functions-can-be-linear` and it's definitely an improvement.

Don't forget to run `npm update`!

**Comment by flannery-denny** [comment]
@schanzer The one time I was able to build the `functions-can-be-linear` deck this evening images were still far larger than the slides.
